In [1]:
!pip install numpy

In [4]:
import numpy as np
# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
print(arr1.shape)  # Output: (5,)
print(type(arr1))  # Output: <class 'numpy.ndarray'>
# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)
# Create a 3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr3)  

1D Array: [1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
